# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc44cae941c67cfd179527ddaafc425237a2b31ec3106e69e6c08c8673a4b6eea8914e4ba8528a39f32bab86e4c9d1c7350a7889362e2c25b0f162ef6ded75e4

test:
  secret_key_base: a602c83850b1d53e48b89febb00aaacba09a267e699725df5fb32c8a5867186bf0df28314240bf21e67b15c5e34ba1f771c6d18b6ece3f94783da5af5279a5fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
